// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EntityFrameworkTask.Models;
using Microsoft.EntityFrameworkCore;

namespace EntityFrameworkTask.Context;

public partial class onboardingContext : DbContext
{
    public onboardingContext(DbContextOptions<onboardingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SimpleTable> SimpleTables { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SimpleTable>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__simpleTa__3213E83F3662330E");

            entity.ToTable("simpleTable");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Value)
                .HasMaxLength(20)
                .HasColumnName("value");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}