// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntityFrameworkTask.Models;

public partial class SimpleTable
{
    public int Id { get; set; }

    public string Value { get; set; }
}