// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using PubSub.Models;

namespace PubSub.Context;

public partial class onboardingContext : DbContext
{
    public onboardingContext(DbContextOptions<onboardingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Message> Messages { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Messages__3214EC07239275EE");

            entity.HasIndex(e => new { e.MessageId, e.SubscriberId, e.Source }, "IX_Messages_MessageId_SubscriberId_Source").IsUnique();

            entity.HasIndex(e => new { e.Source, e.Timestamp }, "IX_Messages_Source_Timestamp");

            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.MessageId)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProcessedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Source)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.SubscriberId)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Timestamp).HasDefaultValueSql("(getutcdate())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}