// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PubSub.Models;

public partial class Message
{
    public long Id { get; set; }

    public string MessageId { get; set; }

    public string SubscriberId { get; set; }

    public string Content { get; set; }

    public string Source { get; set; }

    public DateTime Timestamp { get; set; }

    public DateTime ProcessedAt { get; set; }
}